# html lang
language: zh-cn

# The Index Title
custom_index_title: 博文列表

custom_footer: '<span id="running_times"
  >本站勉强运行: <span id="runDays">0</span>天<span id="runHours"
  >0</span
  >小时<span id="runMins">0</span>分<span id="runSeconds">0</span
  >秒
  <script>
  function runtime() {
  X = new Date("2022/3/07 00:00:00");
  Y = new Date();
  T = Y.getTime() - X.getTime();
  M = 24 * 60 * 60 * 1000;
  a = T / M;
  A = Math.floor(a);
  b = (a - A) * 24;
  B = Math.floor(b);
  c = (b - B) * 60;
  C = Math.floor((b - B) * 60);
  D = Math.floor((c - C) * 60);

  document.getElementById("runDays").innerHTML = A;
  document.getElementById("runHours").innerHTML = B;
  document.getElementById("runMins").innerHTML = C;
  document.getElementById("runSeconds").innerHTML = D;
  }
  setInterval(runtime, 1000);
  </script>
  </span>'

custom_head:
  '  <link rel="apple-touch-icon" sizes="76x76" href="https://unpkg.com/yurik-static@1.0.6/favicon/v2/apple-touch-icon.png">
  <link rel="icon" href="https://unpkg.com/yurik-static@1.0.6/favicon/v2/favicon.ico">'

# main menu navigation
menu:
  主页: /
  关于: /about
  友情链接: /links

post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3

  # 文章在首页的默认封面图，当没有指定 cover 时会使用该图片，若两者都为空则不显示任何图片
  # Path of the default post cover when `cover` is not set. If both are empty, no image will be displayed
  default_cover:
    - /img/covers/1.jpg
    - /img/covers/2.jpg
    - /img/covers/3.jpg
    - /img/covers/4.jpg
    - /img/covers/5.jpg
    - /img/covers/6.jpg
    - /img/covers/7.jpg
    - /img/covers/8.jpg
    - /img/covers/9.jpg
    - /img/covers/10.jpg
    - /img/covers/11.jpg
    - /img/covers/12.jpg
    - /img/covers/13.jpg
    - /img/covers/14.jpg
    - /img/covers/15.jpg

# 静态资源，别动
stylesheets:
  - /css/bootstrap.min.css
  - /css/global.css
  - /css/newsroom.css

# scripts loaded in the end of the body
scripts:
  - /js/navbar.js
  - /js/bootstrap.bundle.min.js
